export interface Channel {
  ttCode: string;
  channelPrice: number;
  isTBS: boolean;
  name: string;
  genre: string[];
  description: string;
  channelType: string[];
  isSVOD: boolean;
  programLanguages: string[];
}

// Generated by https://quicktype.io

export interface Channel {
  ttCode: string;
  channelPrice: number;
  isTBS: boolean;
  name: string;
  genre: string[];
  description: string;
  channelType: string[];
  isSVOD: boolean;
  programLanguages: string[];
  teaserVideo: string;
  topTVShows: TopTVShow[];
}

export interface TopTVShow {
  name: string;
  image: string;
}
